package com.mydroid.chatapp;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.app.ProgressDialog;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.FirebaseDatabase;
import com.mydroid.chatapp.Models.Users;

public class SignUpActivity extends AppCompatActivity {

    private FirebaseAuth mAuth;
    EditText edttxtName, edttxtEmail, edttxtPass;
    Button btnSignUp;
    ProgressDialog progressDialog;
    TextView txtvlogin;
    private FirebaseDatabase mdatabase;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);

        edttxtName = findViewById(R.id.edttxtName);
        edttxtEmail = findViewById(R.id.edttxtEmail);
        edttxtPass = findViewById(R.id.edttxtPass);
        btnSignUp = findViewById(R.id.btnSignUp);
        txtvlogin = findViewById(R.id.txtvlogin);

// Initialize Firebase Auth
        mAuth = FirebaseAuth.getInstance();

        progressDialog =new ProgressDialog(SignUpActivity.this);
        progressDialog.setTitle("Creating Account");
        progressDialog.setMessage("We Are Creating Your Account");

        mdatabase = FirebaseDatabase.getInstance();

        btnSignUp.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                if (!edttxtName.getText().toString().isEmpty() && !edttxtEmail.getText().toString().isEmpty() && !edttxtPass.getText().toString().isEmpty())
                {
                    progressDialog.show();
                    mAuth.createUserWithEmailAndPassword( edttxtEmail.getText().toString(), edttxtPass.getText().toString())
                            .addOnCompleteListener(new OnCompleteListener<AuthResult>()
                            {
                                @Override
                                public void onComplete(@NonNull Task<AuthResult> task)
                                {
                                    progressDialog.dismiss();
                                    if (task.isSuccessful()) {
                                        // Sign in success, update UI with the signed-in user's information
                                        Log.d("TAG", "createUserWithEmail:success");
                                        Users user = new Users(edttxtName.getText().toString() ,edttxtEmail.getText().toString(), edttxtPass.getText().toString());

                                        String userId = task.getResult().getUser().getUid();      // This line retrieves the unique user ID (UID) generated by Firebase for the authenticated user.
                                        mdatabase.getReference().child("Users").child(userId).setValue(user);

                                        Toast.makeText(SignUpActivity.this, "Sign up successful", Toast.LENGTH_SHORT).show();

                                        Intent intent = new Intent(SignUpActivity.this , LoginActivity.class);
                                        startActivity(intent);

                                    } else {
                                        // If sign in fails, display a message to the user.
                                        Log.w("TAG", "createUserWithEmail:failure", task.getException());
                                        Toast.makeText(SignUpActivity.this, "Authentication failed.",
                                                Toast.LENGTH_SHORT).show();
                                    }
                                }
                            });
                }
                else
                {
                    Toast.makeText(SignUpActivity.this, "Enter Credentials", Toast.LENGTH_SHORT).show();
                }
            }
        });

        txtvlogin.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });


    }
}